name: Run PowerShell script

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu.latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        # az extension add --name azure-devops

    - name: Login Azure
      uses: azure/login@v1
      with:
        creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","tenantId":"${{ secrets.TENANT_ID }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}"}'
        enable-AzPSSession: true 

    - name: Run Azure PowerShell Script File
      uses: azure/powershell@v1
      with:
        inlineScript: ./Untitled4.ps1
        azPSVersion: "latest"
     
